### ISSUE TITLE
grant all on database <base> to user <username>;

### ISSUE THREAD

**Issue by s9v** [zserg/flashcard#2]
Running `grant all on database <base> to user <username>;` (from README) returns error:

    ERROR:  syntax error at or near "user"
    LINE 1: grant all on database flashcard to user flashcard;
                                               ^
However, removing "user" and retrying works. I am not familiar with PostgreSQL, but maybe that needs fixing?

**Comment by zserg** [comment]
@oaakx Thanks for feedback. You are right, it's an error in command.
